/**
 * Generates synthetic test media with FFmpeg (no external downloads):
 * videos in every supported container, images, audio, a clip with silence gaps and a clip with a
 * moving high-contrast box (for tracking tests). Output: tests/fixtures/generated/.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const out = path.resolve(__dirname, '..', 'tests', 'fixtures', 'generated');
fs.mkdirSync(out, { recursive: true });
const ffmpeg = process.env.SEVENVID_FFMPEG_PATH ?? 'ffmpeg';

function run(args: string[]): void {
  execFileSync(ffmpeg, ['-hide_banner', '-loglevel', 'error', '-y', ...args], { stdio: 'inherit' });
}

const items: Array<{ name: string; args: string[] }> = [
  { name: 'clip-10s-720p.mp4', args: ['-f', 'lavfi', '-i', 'testsrc2=size=1280x720:rate=30', '-f', 'lavfi', '-i', 'sine=frequency=440:sample_rate=48000', '-t', '10', '-c:v', 'libx264', '-preset', 'veryfast', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-b:a', '128k', '-shortest'] },
  { name: 'clip-5s-1080p.mkv', args: ['-f', 'lavfi', '-i', 'testsrc2=size=1920x1080:rate=25', '-f', 'lavfi', '-i', 'sine=frequency=660:sample_rate=48000', '-t', '5', '-c:v', 'libx264', '-preset', 'veryfast', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-shortest'] },
  { name: 'clip-4s-vp9.webm', args: ['-f', 'lavfi', '-i', 'testsrc2=size=640x360:rate=30', '-f', 'lavfi', '-i', 'sine=frequency=330:sample_rate=48000', '-t', '4', '-c:v', 'libvpx-vp9', '-deadline', 'realtime', '-cpu-used', '8', '-b:v', '500k', '-c:a', 'libopus', '-shortest'] },
  { name: 'clip-3s-mpeg4.avi', args: ['-f', 'lavfi', '-i', 'testsrc2=size=640x480:rate=25', '-f', 'lavfi', '-i', 'sine=frequency=220:sample_rate=44100', '-t', '3', '-c:v', 'mpeg4', '-q:v', '5', '-c:a', 'libmp3lame', '-shortest'] },
  { name: 'clip-6s-prores.mov', args: ['-f', 'lavfi', '-i', 'testsrc2=size=960x540:rate=24', '-f', 'lavfi', '-i', 'sine=frequency=550:sample_rate=48000', '-t', '6', '-c:v', 'prores_ks', '-profile:v', '0', '-c:a', 'pcm_s16le', '-shortest'] },
  { name: 'clip-2s.m4v', args: ['-f', 'lavfi', '-i', 'testsrc2=size=1280x720:rate=30', '-t', '2', '-c:v', 'libx264', '-preset', 'veryfast', '-pix_fmt', 'yuv420p', '-an'] },
  { name: 'vertical-4s.mp4', args: ['-f', 'lavfi', '-i', 'testsrc2=size=1080x1920:rate=30', '-f', 'lavfi', '-i', 'sine=frequency=880:sample_rate=48000', '-t', '4', '-c:v', 'libx264', '-preset', 'veryfast', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-shortest'] },
  { name: 'image.png', args: ['-f', 'lavfi', '-i', 'testsrc2=size=1280x720:rate=1', '-frames:v', '1'] },
  { name: 'photo.jpg', args: ['-f', 'lavfi', '-i', 'mandelbrot=size=1920x1080:rate=1', '-frames:v', '1', '-q:v', '3'] },
  { name: 'tone-3s.wav', args: ['-f', 'lavfi', '-i', 'sine=frequency=440:sample_rate=48000', '-t', '3', '-c:a', 'pcm_s16le'] },
  { name: 'music-8s.mp3', args: ['-f', 'lavfi', '-i', 'sine=frequency=261.63:sample_rate=44100', '-f', 'lavfi', '-i', 'sine=frequency=329.63:sample_rate=44100', '-filter_complex', '[0:a][1:a]amix=inputs=2[a]', '-map', '[a]', '-t', '8', '-c:a', 'libmp3lame', '-b:a', '128k'] },
  // 12 s: tone 0-3s, silence 3-6s, tone 6-8s, silence 8-11s, tone 11-12s (for silence detection/removal tests)
  { name: 'speech-with-silence-12s.mp4', args: ['-f', 'lavfi', '-i', 'testsrc2=size=640x360:rate=30', '-f', 'lavfi', '-i', "sine=frequency=440:sample_rate=48000,volume=enable='between(t,3,6)+between(t,8,11)':volume=0", '-t', '12', '-c:v', 'libx264', '-preset', 'veryfast', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-shortest'] },
  // moving white box on dark background, 6 s (object tracking / blur verification tests)
  { name: 'moving-box-6s.mp4', args: ['-f', 'lavfi', '-i', "color=c=0x202020:size=640x360:rate=30,drawbox=x='40+t*60':y='120+20*sin(t)':w=80:h=80:color=white:t=fill", '-t', '6', '-c:v', 'libx264', '-preset', 'veryfast', '-pix_fmt', 'yuv420p', '-an'] },
];

for (const item of items) {
  const target = path.join(out, item.name);
  if (fs.existsSync(target) && fs.statSync(target).size > 0) continue;
  process.stdout.write(`generating ${item.name}\n`);
  run([...item.args, target]);
}
fs.writeFileSync(path.join(out, 'README.txt'), 'Synthetic test media generated by scripts/gen-fixtures.ts. Safe to delete.\n');
process.stdout.write(`fixtures ready in ${out}\n`);
